(function(){"use strict";
var TI="https://ac.blooket.com/dashboard/86784c3d4c38fcd559c92f38fbadd7a160947de2/_next/static/media/token.8de4e1b8.svg";
var RC={Common:"rgb(160,160,160)",Uncommon:"rgb(75,194,46)",Rare:"rgb(10,20,250)",Epic:"rgb(190,0,255)",Legendary:"rgb(255,170,0)",Chroma:"rgb(0,255,255)",Mystical:"rgb(255,0,128)"};
var RB={Uncommon:"rgb(16,41,10)",Rare:"rgb(8,12,60)",Epic:"rgb(40,5,55)",Legendary:"rgb(60,30,5)",Chroma:"rgb(5,40,50)",Common:"rgb(40,40,40)"};
var RU={Uncommon:"rgb(30,70,20)",Rare:"rgb(20,30,90)",Epic:"rgb(70,20,90)",Legendary:"rgb(90,50,15)",Chroma:"rgb(15,70,80)",Common:"rgb(60,60,60)"};
var DB="rgb(29,4,34)",DU="rgb(55,18,70)";
var OP={spooky:"https://ac.blooket.com/dashboard/86784c3d4c38fcd559c92f38fbadd7a160947de2/_next/static/media/spooky.67d38179.png"};
function bs(n){return"https://ac.blooket.com/marketassets/blooks/"+String(n).toLowerCase().replace(/[^a-z0-9]+/g,"")+".svg"}
function exp(raw){return raw.map(function(p){var s=p.i;return{id:s,name:p.n,cost:p.c,slug:s,png:"https://ac.blooket.com/blookassets/packs/"+s+".png",icon:"https://ac.blooket.com/blookassets/packs/icons/"+s+".svg",bg:"https://ac.blooket.com/blookassets/packs/backgrounds/"+s+".svg",openImg:OP[s]||("https://ac.blooket.com/blookassets/packs/"+s+".png"),blooks:p.b.map(function(b){return{name:b.n,rarity:b.r,chance:b.c,color:RC[b.r]||RC.Uncommon,src:bs(b.n)}})}})}
var P=[],cp=null,up=25,drv=false,ro=0,to=0,ph="idle";
var grid=document.getElementById("packsGrid"),bd=document.getElementById("modalBackdrop"),cb=document.getElementById("closeModal"),qi=document.getElementById("qtyInput"),bql=document.getElementById("buyQtyLabel"),bpl=document.getElementById("buyPriceLabel"),m1=document.getElementById("minus1"),rq=document.getElementById("resetQty"),qs=document.querySelectorAll(".qty-set"),dov=document.getElementById("dropRatesOverlay"),tdb=document.getElementById("toggleDropRates"),pmi=document.getElementById("packMainImg"),ms=document.getElementById("modalShadow"),mt=document.getElementById("modalTitle"),mc=document.getElementById("modalCost"),drl=document.getElementById("dropRatesList"),pib=document.getElementById("packImgBox"),os=document.getElementById("openingScreen"),ps=document.getElementById("packStage"),or=document.getElementById("openingResult"),osq=document.getElementById("openingSquares"),ow=document.getElementById("openingWrapper"),opi=document.getElementById("openingPackImg"),obg=document.getElementById("openingBg");
function cl(n){return Math.max(1,Math.min(100,n||1))}
function fc(c){if(c==null)return"—";var n=Number(c);if(n<1)return n.toFixed(2)+"%";if(Math.abs(n-Math.round(n))<.01)return Math.round(n)+"%";return(Math.round(n*100)/100)+"%"}
function sb(s){return"background-image:url('https://ac.blooket.com/blookassets/packs/backgrounds/"+s+".svg');background-size:cover;background-position:center;"}
function render(){grid.innerHTML="";P.forEach(function(p){var el=document.createElement("div");el.className="pack-container";el.role="button";el.tabIndex=0;el.setAttribute("aria-label","Open "+p.name);el.innerHTML='<div class="pack-img-container" style="'+sb(p.slug)+'"><img class="pack-shadow" src="'+p.icon+'" width="80" height="80" draggable="false" onerror="this.style.display=\'none\'"/><img class="pack-img" src="'+p.png+'" alt="'+p.name+'" width="150" height="165" draggable="false" onerror="this.style.opacity=.35"/></div><div class="pack-bottom"><img src="'+TI+'" width="23" height="23"/>'+p.cost+'</div><div class="pack-overlay"></div>';el.onclick=function(){openM(p)};el.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();openM(p)}};grid.appendChild(el)})}
function ui(q){q=cl(q);qi.value=q;bql.textContent=q;bpl.textContent=q*up;var o=q===1;m1.disabled=o;rq.disabled=o;qs.forEach(function(b){b.disabled=+b.dataset.set===q})}
function openM(p){cp=p;up=p.cost||25;mt.textContent=p.name;mc.textContent=up;pmi.src=p.png;pmi.alt=p.name;pmi.style.visibility="visible";ms.src=p.icon;pib.style.cssText=sb(p.slug)+"display:flex;position:relative;justify-content:center;align-items:center;width:285px;height:285px;";drl.innerHTML=p.blooks.map(function(b){return"<li>"+b.name+": "+fc(b.chance)+"</li>"}).join("");drv=false;dov.classList.remove("show");tdb.textContent="Show Drop Rates";ui(1);bd.classList.add("open");document.body.style.overflow="hidden"}
function closeM(){bd.classList.remove("open");document.body.style.overflow=""}
cb.onclick=closeM;bd.onclick=function(e){if(e.target===bd)closeM()};document.onkeydown=function(e){if(e.key==="Escape"&&bd.classList.contains("open"))closeM()};
qi.oninput=function(){ui(+qi.value)};qi.onchange=function(){ui(+qi.value)};
document.querySelectorAll("[data-add]").forEach(function(b){b.onclick=function(){ui(+qi.value+(+b.dataset.add))}});
m1.onclick=function(){ui(+qi.value-1)};qs.forEach(function(b){b.onclick=function(){ui(+b.dataset.set)}});rq.onclick=function(){ui(1)};
tdb.onclick=function(){drv=!drv;if(drv){dov.classList.add("show");tdb.textContent="Hide Drop Rates";pmi.style.visibility="hidden"}else{dov.classList.remove("show");tdb.textContent="Show Drop Rates";pmi.style.visibility="visible"}};
var CI=35,II=40;for(var i=0;i<49;i++){var sq=document.createElement("div");sq.className="opening-square";var inn=document.createElement("div");inn.className="opening-square-inner";var fr=document.createElement("div");fr.className="opening-square-front";var bk=document.createElement("div");bk.className="opening-square-back";bk.style.filter="brightness("+(40+Math.floor(Math.random()*60))+"%)";if(i===CI){var c=document.createElement("div");c.className="opening-square-content";c.innerHTML='<div class="counter-text" id="gridCounter">1/1</div>';fr.appendChild(c);var c2=c.cloneNode(true);c2.querySelector(".counter-text").removeAttribute("id");bk.appendChild(c2)}else if(i===II){var c3=document.createElement("div");c3.className="opening-square-content";c3.innerHTML='<img id="gridPackIcon" src="" alt="" draggable="false">';fr.appendChild(c3);var c4=c3.cloneNode(true);c4.querySelector("img").removeAttribute("id");bk.appendChild(c4)}inn.appendChild(fr);inn.appendChild(bk);sq.appendChild(inn);osq.appendChild(sq)}
function pick(p){var L=p.blooks,t=0;for(var j=0;j<L.length;j++)t+=+L[j].chance||0;var r=Math.random()*t;for(var k=0;k<L.length;k++){r-=+L[k].chance||0;if(r<=0)return L[k]}return L[L.length-1]}
function updC(){var d=to-ro,tx=(d+1)+"/"+to;if(ro<=0&&ph==="result")tx=to+"/"+to;var el=document.getElementById("gridCounter");if(el)el.textContent=tx}
function setBg(r){osq.style.backgroundColor=RB[r]||DB;var cc=RU[r]||DU;document.querySelectorAll(".opening-square-back").forEach(function(el){el.style.backgroundColor=cc})}
function resetBg(){osq.style.backgroundColor=DB;document.querySelectorAll(".opening-square-back").forEach(function(el){el.style.backgroundColor=DU})}
function showPack(){ph="pack";ps.className="opening-pack-container";ps.style.display="block";or.classList.remove("show");resetBg();opi.src=cp.openImg||cp.png;var ic=document.getElementById("gridPackIcon");if(ic)ic.src=cp.icon;void ps.offsetWidth;ps.classList.add("dropping");updC()}
function showOpen(){closeM();ro=to;os.classList.add("show");document.body.style.overflow="hidden";resetBg();showPack()}
function startOpen(){if(ph!=="pack")return;ph="opening";ps.classList.remove("dropping");ps.classList.add("opening");setTimeout(reveal,550)}
function reveal(){var b=pick(cp);document.getElementById("revealedBlook").src=b.src;document.getElementById("revealedBlook").alt=b.name;document.getElementById("revealedName").textContent=b.name;document.getElementById("revealedRarity").textContent=b.rarity;document.getElementById("revealedRarity").style.color=b.color;document.getElementById("revealedChance").textContent=fc(b.chance);obg.src=cp.bg;ps.style.display="none";ps.className="opening-pack-container";or.classList.add("show");ph="result";ro--;setBg(b.rarity);updC()}
function next(){if(ph==="pack")startOpen();else if(ph==="result"){if(ro>0)showPack();else{os.classList.remove("show");document.body.style.overflow="";ph="idle";resetBg()}}}
ow.onclick=next;document.getElementById("buyBtn").onclick=function(){if(!cp)return;to=cl(+qi.value);ro=to;showOpen()};
fetch("/data/pack-sim-packs.json").then(function(r){return r.json()}).then(function(d){P=exp(d);render()}).catch(function(){grid.innerHTML='<div class="loading-msg">Failed to load packs.</div>'});
})();
