(function(){"use strict";
const TOKEN_ICON="https://ac.blooket.com/dashboard/86784c3d4c38fcd559c92f38fbadd7a160947de2/_next/static/media/token.8de4e1b8.svg";
const RARITY_BG={Uncommon:"rgb(16, 41, 10)",Rare:"rgb(8, 12, 60)",Epic:"rgb(40, 5, 55)",Legendary:"rgb(60, 30, 5)",Chroma:"rgb(5, 40, 50)",Mystical:"rgb(50, 5, 30)",Common:"rgb(40, 40, 40)"};
const RARITY_CUBE={Uncommon:"rgb(30, 70, 20)",Rare:"rgb(20, 30, 90)",Epic:"rgb(70, 20, 90)",Legendary:"rgb(90, 50, 15)",Chroma:"rgb(15, 70, 80)",Mystical:"rgb(80, 20, 50)",Common:"rgb(60, 60, 60)"};
const DEFAULT_BG="rgb(29, 4, 34)",DEFAULT_CUBE="rgb(55, 18, 70)";
let PACKS=[],currentPack=null,unitPrice=25,dropRatesVisible=false,remainingOpens=0,totalOpens=0,openingPhase="idle";
const grid=document.getElementById("packsGrid"),backdrop=document.getElementById("modalBackdrop"),closeBtn=document.getElementById("closeModal"),qtyInput=document.getElementById("qtyInput"),buyQtyLabel=document.getElementById("buyQtyLabel"),buyPriceLabel=document.getElementById("buyPriceLabel"),minus1=document.getElementById("minus1"),resetQty=document.getElementById("resetQty"),qtySetBtns=document.querySelectorAll(".qty-set"),dropOverlay=document.getElementById("dropRatesOverlay"),toggleDropBtn=document.getElementById("toggleDropRates"),packMainImg=document.getElementById("packMainImg"),modalShadow=document.getElementById("modalShadow"),modalTitle=document.getElementById("modalTitle"),modalCost=document.getElementById("modalCost"),dropRatesList=document.getElementById("dropRatesList"),openingScreen=document.getElementById("openingScreen"),packStage=document.getElementById("packStage"),openingResult=document.getElementById("openingResult"),openingSquares=document.getElementById("openingSquares"),openingWrapper=document.getElementById("openingWrapper"),openingPackImg=document.getElementById("openingPackImg"),openingBg=document.getElementById("openingBg");
function clamp(n){return Math.max(1,Math.min(100,n||1))}
function formatChance(c){if(c==null)return"—";const n=Number(c);if(n<1)return n.toFixed(2)+"%";if(Math.abs(n-Math.round(n))<0.01)return Math.round(n)+"%";return(Math.round(n*100)/100)+"%"}
function renderPackCards(){grid.innerHTML="";PACKS.forEach(function(pack){const el=document.createElement("div");el.className="pack-container";el.setAttribute("role","button");el.tabIndex=0;el.setAttribute("aria-label","Open "+pack.name);el.innerHTML='<div class="pack-name-badge">'+pack.name.replace(/ Pack$/,"")+'</div><div class="pack-img-container"><img class="pack-shadow" src="'+pack.icon+'" alt="" width="80" height="80" onerror="this.style.display=\'none\'" /><img class="pack-img" src="'+pack.png+'" alt="'+pack.name+'" width="150" height="165" onerror="this.style.opacity=0.3" /></div><div class="pack-bottom"><img class="pack-price-icon" src="'+TOKEN_ICON+'" alt="Token" width="23" height="23" />'+pack.cost+'</div><div class="pack-overlay"></div>';el.addEventListener("click",function(){openModal(pack)});el.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();openModal(pack)}});grid.appendChild(el)})}
function updateUI(qty){qty=clamp(qty);qtyInput.value=qty;buyQtyLabel.textContent=qty;buyPriceLabel.textContent=qty*unitPrice;const isOne=qty===1;minus1.disabled=isOne;resetQty.disabled=isOne;qtySetBtns.forEach(function(btn){btn.disabled=parseInt(btn.dataset.set,10)===qty})}
function openModal(pack){currentPack=pack;unitPrice=pack.cost||25;modalTitle.textContent=pack.name;modalCost.textContent=unitPrice;packMainImg.src=pack.png;packMainImg.alt=pack.name;packMainImg.style.visibility="visible";modalShadow.src=pack.icon;dropRatesList.innerHTML=pack.blooks.map(function(b){return"<li>"+b.name+": "+formatChance(b.chance)+"</li>"}).join("");dropRatesVisible=false;dropOverlay.classList.remove("show");toggleDropBtn.textContent="Show Drop Rates";updateUI(1);backdrop.classList.add("open");document.body.style.overflow="hidden"}
function closeModal(){backdrop.classList.remove("open");document.body.style.overflow=""}
closeBtn.addEventListener("click",closeModal);backdrop.addEventListener("click",function(e){if(e.target===backdrop)closeModal()});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&backdrop.classList.contains("open"))closeModal()});qtyInput.addEventListener("input",function(){updateUI(parseInt(qtyInput.value,10))});qtyInput.addEventListener("change",function(){updateUI(parseInt(qtyInput.value,10))});document.querySelectorAll("[data-add]").forEach(function(btn){btn.addEventListener("click",function(){updateUI(parseInt(qtyInput.value,10)+parseInt(btn.dataset.add,10))})});minus1.addEventListener("click",function(){updateUI(parseInt(qtyInput.value,10)-1)});qtySetBtns.forEach(function(btn){btn.addEventListener("click",function(){updateUI(parseInt(btn.dataset.set,10))})});resetQty.addEventListener("click",function(){updateUI(1)});toggleDropBtn.addEventListener("click",function(){dropRatesVisible=!dropRatesVisible;if(dropRatesVisible){dropOverlay.classList.add("show");toggleDropBtn.textContent="Hide Drop Rates";packMainImg.style.visibility="hidden"}else{dropOverlay.classList.remove("show");toggleDropBtn.textContent="Show Drop Rates";packMainImg.style.visibility="visible"}});
const COUNTER_INDEX=35,ICON_INDEX=40;
for(let i=0;i<49;i++){const sq=document.createElement("div");sq.className="opening-square";const inner=document.createElement("div");inner.className="opening-square-inner";const front=document.createElement("div");front.className="opening-square-front";const back=document.createElement("div");back.className="opening-square-back";back.style.filter="brightness("+(40+Math.floor(Math.random()*60))+"%)";if(i===COUNTER_INDEX){const content=document.createElement("div");content.className="opening-square-content";content.innerHTML='<div class="counter-text" id="gridCounter">1/1</div>';front.appendChild(content);const contentB=content.cloneNode(true);contentB.querySelector(".counter-text").removeAttribute("id");back.appendChild(contentB)}else if(i===ICON_INDEX){const content=document.createElement("div");content.className="opening-square-content";content.innerHTML='<img id="gridPackIcon" src="" alt="" draggable="false">';front.appendChild(content);const contentB=content.cloneNode(true);contentB.querySelector("img").removeAttribute("id");back.appendChild(contentB)}inner.appendChild(front);inner.appendChild(back);sq.appendChild(inner);openingSquares.appendChild(sq)}
function pickBlook(pack){const list=pack.blooks;let total=0;for(let i=0;i<list.length;i++)total+=list[i].chance;let r=Math.random()*total;for(let i=0;i<list.length;i++){r-=list[i].chance;if(r<=0)return list[i]}return list[list.length-1]}
function updateCounter(){const done=totalOpens-remainingOpens;let text=(done+1)+"/"+totalOpens;if(remainingOpens<=0&&openingPhase==="result")text=totalOpens+"/"+totalOpens;const el=document.getElementById("gridCounter");if(el)el.textContent=text}
function setBgColor(rarity){openingSquares.style.backgroundColor=RARITY_BG[rarity]||DEFAULT_BG;const cubeColor=RARITY_CUBE[rarity]||DEFAULT_CUBE;document.querySelectorAll(".opening-square-back").forEach(function(el){el.style.backgroundColor=cubeColor})}
function resetBgColor(){openingSquares.style.backgroundColor=DEFAULT_BG;document.querySelectorAll(".opening-square-back").forEach(function(el){el.style.backgroundColor=DEFAULT_CUBE})}
function showPack(){openingPhase="pack";packStage.className="opening-pack-container";packStage.style.display="block";openingResult.classList.remove("show");resetBgColor();openingPackImg.src=currentPack.png;const iconEl=document.getElementById("gridPackIcon");if(iconEl)iconEl.src=currentPack.icon;void packStage.offsetWidth;packStage.classList.add("dropping");updateCounter()}
function showOpening(){closeModal();remainingOpens=totalOpens;openingScreen.classList.add("show");document.body.style.overflow="hidden";resetBgColor();showPack()}
function startOpenAnim(){if(openingPhase!=="pack")return;openingPhase="opening";packStage.classList.remove("dropping");packStage.classList.add("opening");setTimeout(function(){revealBlook()},550)}
function revealBlook(){const b=pickBlook(currentPack);document.getElementById("revealedBlook").src=b.src;document.getElementById("revealedBlook").alt=b.name;document.getElementById("revealedName").textContent=b.name;document.getElementById("revealedRarity").textContent=b.rarity;document.getElementById("revealedRarity").style.color=b.color;document.getElementById("revealedChance").textContent=formatChance(b.chance);openingBg.src=currentPack.bg;packStage.style.display="none";packStage.className="opening-pack-container";openingResult.classList.add("show");openingPhase="result";remainingOpens--;setBgColor(b.rarity);updateCounter()}
function nextOpeningStep(){if(openingPhase==="pack")startOpenAnim();else if(openingPhase==="result"){if(remainingOpens>0)showPack();else{openingScreen.classList.remove("show");document.body.style.overflow="";openingPhase="idle";resetBgColor()}}}
openingWrapper.addEventListener("click",nextOpeningStep);document.getElementById("buyBtn").addEventListener("click",function(){if(!currentPack)return;totalOpens=clamp(parseInt(qtyInput.value,10));remainingOpens=totalOpens;showOpening()});
fetch("/data/pack-sim-packs.json").then(function(r){return r.json()}).then(function(data){PACKS=data;renderPackCards()}).catch(function(){grid.innerHTML='<div class="loading-msg">Failed to load packs.</div>'});
})();
